BROADCAST_CHIEF_COMMAND = "broadcast_chief_command"
BROADCAST_CHIEF_SELECT_BUS = "broadcast_chief_select_bus_"
BROADCAST_CHIEF_SEND = "broadcast_chief_send"
BROADCAST_CHIEF_CANCEL = "broadcast_chief_cancel"
EXPORT_CHIEF_COMMAND = "export_chief_command"
EXPORT_CHIEF_SELECT_BUS = "export_chief_select_bus_"
